### PR TITLE
After feature

### PR DESCRIPTION
**Pull request by Faizansaeed12**
This my code from branch Lab_2 after doing lab manual

### CODE REVIEW

**Comment by shahwar-khalid** [comment]
@Faizansaeed12 
user model us missing.
user has many `companies` and company belongs to `user`

**Comment by shahwar-khalid** [comment]
@Faizansaeed12 Did you know about `rails db:rollback` command?

**Comment by shahwar-khalid** [comment]
@Faizansaeed12 Callbacks are missing.

**Comment by shahwar-khalid** [comment]
@Faizansaeed12 Seed file is missing

**Comment by Faizansaeed12** [comment]
> @Faizansaeed12 Did you know about `rails db:rollback` command?

**Comment by Faizansaeed12** [comment]
> @Faizansaeed12 Did you know about `rails db:rollback` command?

I had data in table, rollback could have deleted that and I had to re enter all data and i have to change some data types thats why i create migrations and through them i change my data type from decimal to float

**Pull request closed without merging**
